### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by rickygm** [grellis00/asterisk-security#1]
Hi, try running the script 

 perl asterisk-security.pl 
Missing right curly or square bracket at asterisk-security.pl line 71, at end of line
syntax error at asterisk-security.pl line 71, at EOF

**Comment by grellis00** [comment]
Should be fixed, thanks.

**Comment by rickygm** [comment]
Hi , I no longer see the previous error, I think it is repaired, but it would be necessary to make some adjustments for a better stop, see some attacks on my pbx:

NOTICE[2086] chan_sip.c: Registration from '"601" <sip:601@200.62.X.X>' failed for '46.105.117.221:5206' - Wrong password
[2020-05-26 15:53:33] NOTICE[2086] chan_sip.c: Registration from '"6001" <sip:6001@200.62.X.X>' failed for '46.105.117.221:5206' - Wrong password
[2020-05-26 15:53:33] NOTICE[2086] chan_sip.c: Registration from '"701" <sip:701@200.62.X.X>' failed for '46.105.117.221:5206' - Wrong password

perl asterisk-security.pl 
Statement unlikely to be reached at asterisk-security.pl line 59.
	(Maybe you meant system() when you said exec()?)
no failed registrations.
You have new mail in /var/spool/mail/root

run the script but it doesn't detect the attack, and it refers to line 59, I don't know if there will be something to modify in the attempts.
Another assurance, I am not an expert in perl, but you could create an ipset list to work with iptables, I think it has better performance.

something like that:

ipset create "asterisk-black" hash:ip hashsize 2048 timeout 14400

it's just a suggestion

**Comment by grellis00** [comment]
Hi Ricky,

There is definitely work that can be done on this project. Full disclaimer (this is also in readme.md) 
 I'm not the original author of this, and I'm not sure who is. At my previous  employer  I found the script on our PBX's however it was broken (had programming errors) and not  doing  a whole  lot.  I've  since seen this reposted on a bunch  of forums and  github accounts (many of  them also broken) - so not sure  who actually wrote it. I did however  clean up some of the errors and got it functional. During the course of my employment I modified this  heavily with a bunch more  rules,  IP whitelisting, etc. and some greater efficiency. This code  is not  that  however. When I departed I did not think to grab a complete copy. Not sure if I would have even been legally allowed to keep it due to contracts stating  that they owned any development I did during the course of my employment.

I still work in VoIP, but I  no longer have access to an  asterisk environment or asterisk logs. So I can't  easily test and update the code. There's also different error  syntax in the logs, depending on which version of  asterisk  you're  using. It may be that you're using a newer version of asterisk than we were

I'm  happy  to see if I can write  some  rules (if you can  provide more examples of what im checking for), but I won't be able to test them in a live scenario.

**Comment by rickygm** [comment]
I understand your point, I am using version 13, I don't know if I can pass you part of the log, in a paste bin and you could do more tests

**Comment by grellis00** [comment]
If you want to send me  part of the log, it would make it  a bit easier on me. Especially  if there's more than the one thing you provided above.

As for  the  one you  provided above, I just committed a change with a new rule that *should* cover it,  provided I haven't made any  mistakes. Might try it  out?

I'm not 100% sure  on  this error: 
Statement unlikely to be reached at asterisk-security.pl line 59.
(Maybe you meant system() when you said exec()?)
Im sure I was using exec successfully. Not sure what's prompting this.maybe different perl versions?depreciation  of something?

**Comment by rickygm** [comment]
grellis00 I do not know if you care, could you provide me with your email, I would not like to paste the log of my pbx in public.
version of perl

perl-5.16.3-294.el7_6.x86_64

**Comment by grellis00** [comment]
geoffellis00 [at] gmail.com

**Comment by rickygm** [comment]
ok, i will send it in a few minutes.

I did the test with the last change you made and I see that it works, only that having many brute force attacks would be a good option to put them in an ipset list, and adding a whitelist of course.

**Comment by rickygm** [comment]
please check your email, send the logs

**Comment by grellis00** [comment]
Ya, I'm sure there's more efficient ways of doing this. I have seen this script go through log files with several million lines of logs though fairly quickly.  The first time  I  actually ran this in a production environment, it detected  an attack from a single IP that had made 1.2million attempts. So i  mean, it's probably not scalable up to an international voip network or anything, but i think it should handle most small/medium/large-ish PBX's.

also, I got the log file.

**Comment by rickygm** [comment]
I think so, my pbx is small, but if you look at the log the number of attacks, now I come across this script that you uploaded, because the fail2ban is not working very well for me and decides to try it, I am not an expert in voip, I am enthusiastic but I have already played several years with asterisk and I know it is very attacked, thanks for the help.
